"""Generate content-addressed WebP images and WOFF2 fonts. Originals stay intact.

Run with Python + Pillow, fonttools[woff], and the gif2webp executable installed.
"""
from pathlib import Path
import hashlib
import json
import re
import subprocess
import tempfile

from PIL import Image
from fontTools.ttLib import TTFont

DIST = Path(__file__).resolve().parents[1] / 'dist'
ASSETS = DIST / 'assets'
OUTPUT = ASSETS / 'optimized'
OUTPUT.mkdir(exist_ok=True)


def publish(path, stem, suffix):
    data = path.read_bytes()
    digest = hashlib.sha256(data).hexdigest()[:12]
    target = OUTPUT / f'{stem}.{digest}.{suffix}'
    target.write_bytes(data)
    return str(target.relative_to(DIST))


media = {}
fonts = {}
with tempfile.TemporaryDirectory() as temp:
    temp = Path(temp)
    for source in sorted(ASSETS.glob('*.jpg')):
        with Image.open(source) as original:
            original = original.convert('RGB')
            variants = []
            for width in sorted({min(w, original.width) for w in [240, 480, 960, 1440]}):
                image = original.resize((width, round(original.height * width / original.width)), Image.Resampling.LANCZOS)
                target = temp / 'image.webp'
                image.save(target, 'WEBP', quality=80 if width > 240 else 65, method=6)
                variants.append((width, publish(target, f'{source.stem}-{width}', 'webp')))
            media[str(source.relative_to(DIST))] = {
                'src': variants[-1][1],
                'srcset': ', '.join(f'{url} {width}w' for width, url in variants if width > 240),
                'thumb': variants[0][1],
                'width': original.width,
                'height': original.height,
            }
    for source in sorted(ASSETS.glob('*.gif')):
        target = temp / 'animation.webp'
        subprocess.run(['gif2webp', '-quiet', '-lossy', '-q', '80', '-m', '6', str(source), '-o', str(target)], check=True)
        with Image.open(source) as original:
            media[str(source.relative_to(DIST))] = {
                'src': publish(target, source.stem, 'webp'),
                'width': original.width, 'height': original.height,
            }
    for name in ['instrument-serif', 'manrope-regular', 'manrope-semibold', 'manrope-bold']:
        font = TTFont(ASSETS / f'{name}.ttf')
        font.flavor = 'woff2'
        target = temp / 'font.woff2'
        font.save(target)
        fonts[name] = publish(target, name, 'woff2')

(DIST / 'media.js').write_text('// Generated by tools/optimize_assets.py; original URLs remain stable Capture IDs.\nwindow.ELSEWHERE_MEDIA=' + json.dumps(media, separators=(',', ':')) + ';\n')
(OUTPUT / 'fonts.json').write_text(json.dumps(fonts, indent=2) + '\n')
# Keep preload URLs and @font-face sources aligned when a font changes.
for filename in ['index.html', 'style.css']:
    path = DIST / filename
    content = path.read_text()
    for name, url in fonts.items():
        content = re.sub(r'assets/(?:optimized/)?' + re.escape(name) + r'(?:\.[a-f0-9]{12})?\.(?:ttf|woff2)', url, content)
    content = content.replace('font/ttf', 'font/woff2').replace("format('truetype')", "format('woff2')")
    path.write_text(content)
print(f'Generated {len(media)} image entries and {len(fonts)} fonts.')
